### PR TITLE
Update RedHat firewalld handling

### PR DESCRIPTION
**Pull request by mto79**
## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Just open port by service in firewall but doesn't do anything possible because of boolean

## What is the new behavior?

Just implement service and nog with_items
Deleted with_items directive because no {{ item }} and the subject is firewall service en not ports

### CODE REVIEW

**Comment by robin-tribe29** [comment]
Hi @mto79. We do appreciate every contribution, but there are two issues with this one:
1. Your pull request is poorly formatted, I can barely understand what it says.
2. If you take a look at `vars/RedHat.yml`, you will realize, that the loop actually makes sense.
If you want to rename the task to reflect, what it does, I would support that.
If you want to extend the port list, I would also support that.

But in this state, I will have to close the PR.

**Comment by mto79** [comment]
Hi Robin, with a loop , you expect an item . The directive is only on the httpd service .. not to open the port.

**Comment by mto79** [comment]
My apologies, it is of course the Python module that is handling the loop under the hood in the xml file of the service. So the with_items than Will make sense.. forgetting how dodgy ansible can be. So used to

- ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ ports_to_open }}"

Sorry again my bad.

**Comment by robin-tribe29** [comment]
Your solution in this PR does not make sense, but as far as I understand, you uncovered an actuall issue here.
The task does not respect the variable it loops over.
@diademiemi I think you have deeper insight into firewalld. Does the code in the last comment from @mto79 make sense, or are we missing something? Just want to make sure, we get the right grip on this.

**Comment by diademiemi** [comment]
Yes, the code in this comment does make sense. The initial pull request reverts it to wht it was before I made it a loop.
I see the current code is indeed broken, if I had to guess something might have gone wrong while merging? Not quite sure how this could have happened but it does look like half the code is from when it only opened port 80 that and the other half is for when I made it a loop.

I think the best code for this would be:
```yaml
- name: "Open firewall ports."
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ checkmk_server_ports }}"
  when: checkmk_server_configure_firewall | bool
```

**Comment by robin-tribe29** [comment]
I messed up pushing to this PR, but I pushed the change to devel: 111092bedf3ed01e5667cfec2424d63514562e8c
Closing this now. Thanks everyone!

**Pull request closed without merging**
