### PR TITLE
module:folder, Add update_attributes, remove_attributes and ansible check_mode; Fix #289

### LINKED ISSUE #289: [BUG] module "folder" not idempotent when setting attributes
I'd like to create a folder with some attributes set:
```
    - name: create single folder
      folder:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        path: /compute/testme
        name: testme
        attributes:
          contactgroups:
            groups:
              - "testme-admin"
            recurse_perms: true
        state: present
      delegate_to: localhost
```
On first use, this task succeeds and does exactly what I want. Repeating this task leads to an error
```
fatal: [testps -> localhost]: FAILED! => {"changed": false, "msg": "Error calling API. HTTP code 400. Details: b'{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: name\", \"fields\": {\"name\": [\"Unknown field.\"]}}', "}
```
Without the "attributes" part, the task is idempotent and works as expected.

### PR DESCRIPTION
**Pull request by msekania**
Adds support of `update_attributes` and `remove_attributes`.

Adds ansible check_mode functionality

## Pull request type

Please check the type of change your PR introduces:

- [X] Bugfix
- [X] Feature
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- Do not support `update_attributes` and `remove_attributes` ;
- No ansible check_mode.
- Idempotency #289 

## What is the new behavior?

- Adds `update_attributes` and `remove_attributes` features;
- Adds ansible check_mode.
- Fixes #289 (not finished yet!)

### CODE REVIEW

**Comment by msekania** [comment]
`update_attributes` and  `remove_attributes` are idempotent

**Comment by robin-checkmk** [comment]
@msekania thanks for the PR! Is the draft state intended and are you still working on this, or is it ready for review?

**Comment by msekania** [comment]
> @msekania thanks for the PR! Is the draft state intended and are you still working on this, or is it ready for review?

@robin-checkmk 

As I said, idempotency with `update_attributes` and `remove_attributes` is there!
With `attributes` I still do not have a solution.

And currently I am reducing several REST API calls to a single one. Almost done

**Comment by msekania** [comment]
@robin-checkmk 

one can remove draft status

**Comment by msekania** [comment]
@robin-checkmk, @lgetwan 

@robin-checkmk 
There is a following problem:

input
```json
{'contactgroups': {'groups': ['test_contact_group'], 'recurse_perms': True}}
```

return value
```json
{'contactgroups': {'groups': ['test_contact_group'], 'use': False, 'use_for_services': False, 'recurse_use': False, 'recurse_perms': True}}
```

do not match although they mean the same!
Issues with returned default values.

module:host is also affected!

Indirect solution with `update_attributes` instead of `attribures`

**Pull request closed without merging**
