### PR TITLE
Update host.py

### PR DESCRIPTION
**Pull request by shock0572**
Added the possibility to use an ip_address when adding a host

### CODE REVIEW

**Comment by robin-tribe29** [comment]
Hi @shock0572 and thank you for your contribution!
I merged it for now, but there will be some additional changes necessary, regarding documentation and possibly some naming. Just for your awareness, so you can keep an eye on the updates to come.

**Comment by shock0572** [comment]
Of course, my code was merely a hack!
Thank you for the merge though, I will take a look here

**Comment by robin-tribe29** [comment]
Quick follow up: @lgetwan reworked the `host` module and created a proper implementation of host attributes in c4cbf3a6552557a6c1cc24320e6910cb0d078a60. Just for your awareness @shock0572.

**Comment by shock0572** [comment]
thank you!

**Pull request merged**
