### PR TITLE
module downtimes: better parameter handling

### PR DESCRIPTION
**Pull request by lgetwan**
## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

#243 
The parameters start_after and end_after do not accept string values, which might sometimes be necessary, when variables are used.

## What is the new behavior?

- Strings are automatically being converted to integers.

### CODE REVIEW

**Comment by robin-tribe29** [comment]
@ogaida for your information, if you want to take a look. :)

I will take care of the sanity checks. :muscle:

**Comment by ogaida** [comment]
why do you ask? python2 is not supported at all.

**Review by robin-tribe29 — APPROVED** [review]
Looks fine by me.

We will take a brief break from merges, but will be back within two weeks.

**Comment by robin-tribe29** [comment]
> why do you ask? python2 is not supported at all.

After your input on changing some else's code without a word, I felt like it was appropriate to give you a chance to comment. If this change is good for you, that's great. :)

Regarding Python: Ansible 2.11 and 2.12 still support Python 2.6, hence we want to stay compatible. Of course the language version itself is end of life.

**Pull request merged**
