### PR TITLE
Functional workaround for creating an existing host

### PR DESCRIPTION
**Pull request by lupusAnimus**
This is a functional workaround for the case, that you want to create an already existing host

## Pull request type
Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by robin-tribe29** [comment]
@lupusAnimus can you please explain your change? I see no improvement here, the current implementation works just fine.

**Comment by lupusAnimus** [comment]
Hi Robin, as far as I know, it is a difference if you use 'is' or '==' as operator. In my case, I always got the error "template error while templating string: no test named 'true'." and after replacing 'is' with '==' it just worked

**Comment by robin-tribe29** [comment]
> Hi Robin, as far as I know, it is a difference if you use 'is' or '==' as operator. In my case, I always got the error "template error while templating string: no test named 'true'." and after replacing 'is' with '==' it just worked

Interesting, which Ansible version are you using?

**Comment by lupusAnimus** [comment]
Right at the moment, we are using ansible-playbook 2.9.27

**Comment by robin-tribe29** [comment]
> Right at the moment, we are using ansible-playbook 2.9.27

That might explain it. Probably something changed in a more recent version.
As we support Ansible from Version 2.11 with this collection, I am compelled to close this PR.
Unless you have anything else to add here.

**Comment by lupusAnimus** [comment]
Ok, this may explain it. So you can close this PR and I try to update our environment. Thanks

**Comment by robin-tribe29** [comment]
As this came up internally too, I will investigate once more and see, if I can find a way to make this more resilient.

**Comment by robin-tribe29** [comment]
This PR seem valid after all, so I will merge it.

**Comment by robin-tribe29** [comment]
One more update: It seems like this issue does not occur, then Ansible is installed through `pip`.
@lupusAnimus can you confirm, that your Ansible was installed through the OS package manager?
That still does not explain the situation, but at least we have symptoms.

**Comment by lupusAnimus** [comment]
Right, my Ansible was installed via the systems repositories on a CentOS 7 and another one on CentOS 8

**Pull request merged**
