### PR TITLE
Bugfix CentOS support in server role

### PR DESCRIPTION
**Pull request by robin-tribe29**
## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
Installation on CentOS is not possible, as EPEL is not enabled on CentOS.

### CODE REVIEW

**Comment by robin-tribe29** [comment]
@diademiemi can you double-check this please? I realized that support for CentOS was broken, because EPEL would not be installed after your last changes. My tests with CentOS work now, maybe you can ensure RHEL is still working. Thanks!

**Comment by diademiemi** [comment]
I'll have a look at this later today

**Comment by diademiemi** [comment]
Sorry for the long wait, I got busy and didn't have the chance to look at this. I just tested this branch against my RHEL boxes and they still work as expected

**Comment by robin-tribe29** [comment]
No worries! Thanks for taking the time! :+1:

**Pull request merged**
