### PR TITLE
Increase HTTP timeout for discovery from 10 to 60 seconds

### PR DESCRIPTION
**Pull request by neffs**
## Pull request type

Please check the type of change your PR introduces:

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
Discovery for a SNMP host often won't finish within the 10 seconds HTTP timeout used by fetch_url, resulting in an error.

## What is the new behavior?
Set timeout to 60 seconds.

### CODE REVIEW

**Review by lgetwan — APPROVED** [review]
Good idea.
Thanks for your contribution!

**Comment by lgetwan** [comment]
@robin-tribe29 can you please check why the sanity checks are failing? There seems to be a version conflict in our devel branch.

**Comment by robin-tribe29** [comment]
I will investigate and update as soon as I got something.

**Comment by robin-tribe29** [comment]
Sanity checks fixed, waiting for further review by @lgetwan.

**Comment by lgetwan** [comment]
Hi @neffs,

to me, it looks like the sanity check is complaining, that the module plugins/modules/discovery.py is executable. Can you please check that and change it if true? Let's see if this makes the sanity check happy.

Best regards
Lars

**Comment by neffs** [comment]
Hi @lgetwan
> to me, it looks like the sanity check is complaining, that the module plugins/modules/discovery.py is executable. Can you please check that and change it if true? Let's see if this makes the sanity check happy.

You're right! Not sure how that happened... Should be fixed now!

**Pull request merged**
