### PR TITLE
Fix ansible-lint findings.

### PR DESCRIPTION
**Pull request by robin-tribe29**
## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

ansible-lint fails with several issues.

## What is the new behavior?

- Fix indentation
- Fix FQCN
- Fix ignore_errors usage

### CODE REVIEW

**Comment by robin-tribe29** [comment]
@diademiemi can you take a look at the removal of `ignore_errors` and maybe figure out a way to achieve whatever you tried to achieve with `changed_when` or `failed_when`?

**Comment by diademiemi** [comment]
Sure, I think it can just be removed. I think it shouldn't fail unless firewalld isn't running, but if that's the case you should just disable that boolean on the host.

**Comment by robin-tribe29** [comment]
Perfect. If this comes up again, we can still implement a detection for firewalld.

**Comment by diademiemi** [comment]
Yes, I think I had one in the server task before it became a boolean, could probably get that from past commits if wanted.

**Comment by robin-tribe29** [comment]
Yeah, I have the logic in mind, but little time. :sweat_smile: 
I think we are good for now.

**Pull request merged**
