### PR TITLE
Add host_tag_group module.

### PR DESCRIPTION
**Pull request by muehlings**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

This PR includes a new module, the host_tag_group module.

With this module you can list, create, update and delete host_tag_groups in a site.

## What is the new feature?

- Create a new host_tag_group in a site.
- Update/delete an existing host_tag_group in a site.
- Read is always performed the get the state of the host_tag_group (present/absent)

## Other information

- Implements GET/POST/PUT/DELETE from Checkmk API for Host tag groups (check_mk/api/1.0/ui/#/Host tag groups)
- Tested with Checkmk 2.0.0p23 CME and ansible [core 2.11.12]

### CODE REVIEW

**Comment by robin-tribe29** [comment]
Hi @muehlings and thanks a lot for your contribution!
We will take a look at the module and review it.
While you wait, please fix findings from the checks. Also, take a look at the integration tests of another module, maybe you can already implement those for this module too?

**Comment by robin-tribe29** [comment]
@muehlings I might be missing something, but I would like to name the module plainly `tag`. There should be no naming conflicts, as we only use that term for the very objects, this module should manage. Can you agree with that approach and implement the changes? I would schedule your module for merge into version 0.11.0 then.

**Comment by muehlings** [comment]
Hello @robin-tribe29 

> @muehlings I might be missing something, but I would like to name the module plainly `tag`. There should be no naming conflicts, as we only use that term for the very objects, this module should manage. Can you agree with that approach and implement the changes? I would schedule your module for merge into version 0.11.0 then.

I wanted to stay in the original naming context of the API (/objects/**host_tag_group** and ​/domain-types​/**host_tag_group**​/collections​/all). The tags are the list items inside the host_tag_group (like "ESXi" and "HyperV" in my example).

The YAML-hierarchy will stay clearer with my naming approach:
```
    host_tag_group: 
      ident: Virtualization
      tags:
        - ident: No_Virtualization
          title: No Virtualization
        - ident: ESXi
          title: ESXi
```
instead of
```
    tag: # singular, no posibility to identify this as a group or aggregation of other items
      ident: Virtualization
      tags: # plural, here is the item list
        - ident: No_Virtualization
          title: No Virtualization
        - ident: ESXi
          title: ESXi
```

For the case I am going to change the module name:
Should I change the method names and/or YAML accordingly?

Greetings

**Comment by robin-tribe29** [comment]
Hi @muehlings! We had an internal discussion and want to go with the module name `tag_group`.
Are you okay with my further suggestions, mentioned above? Then the result, I would want to go for, would look like this:
```
tribe29.checkmk.tag_group:
  name: Virtualization
  choices:
    - id: No_Virtualization
      title: No Virtualization
    - id: ESXi
      title: ESXi
```
If we can do the refactor quickly, you are still in for a release of this feature with version `0.11.0`.

**Comment by robin-tribe29** [comment]
Yes, that is exactly, what I was thinking. :+1:

**Comment by robin-tribe29** [comment]
@muehlings: Quick hint: You can run `ansible-test sanity --docker default` locally, to verify everything is well. I think it should be installed alongside Ansible. You will need working Docker, however.

**Comment by robin-tribe29** [comment]
We are targeting to merge this for the 0.11.0 release.
0.10.0 is pending some clarifications, but I am confident, that those will soon be resolved, and we can start preparing the next release. Stay tuned. :v:

**Pull request merged**
