### PR TITLE
Feature contacts groups

### PR DESCRIPTION
**Pull request by msekania**
Additional plugin that manages contact groups. In essence host_group.py with 'host' exchanges with 'contact'.
Rest API of both host and contact groups are "almost" identical.

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: `e.g. #1`

## What is the new behavior?

- manage contact groups in Checkmk (create/modify/delete)
- bulk and single mode for contact group management

## Other information

```yaml
- name: "Create a single contact group."
  tribe29.checkmk.contact_group:
    server_url: "http://localhost/"
    site: "my_site"
    automation_user: "automation"
    automation_secret: "$SECRET"
    contact_group_name: "my_contact_group"
    title: "My Contact Group"
    state: "present"
  delegate_to: localhost

- name: "Create contact groups."
  tribe29.checkmk.contact_group:
    server_url: "http://localhost/"
    site: "my_site"
    automation_user: "automation"
    automation_secret: "$SECRET"
    contact_groups: "my_contact_groups"
    title: "My Contact Group"
    state: "present"
  vars:
    my_contact_groups:
      - name: "contact_one"
        title: "Contact One"
      - name: "OnCall"
        title: "Not on Sundays"
  delegate_to: localhost

- name: "Check_MK: create/register rules, which assign all servers in the given folder to the given contact group"
  tribe29.checkmk.rule:
    server_url: "http://localhost/"
    site: "my_site"
    automation_user: "automation"
    automation_secret: "$SECRET"
    ruleset: "host_contactgroups"
    rule:
        folder: "/My/Host_Groups"
        conditions: {
            "host_labels": [],
            "host_tags": [],
            "service_labels": []
        }
        properties: {
            "disabled": false,
        }
        value_raw: "'my_contact_group'"
    state: "present"
  run_once: 'true'
  delegate_to: localhost
```

### CODE REVIEW

**Comment by msekania** [comment]
Since rest API is almost identical, in essence
```bash
sed 's/host\([ _g]\)/contact\1/g host_group.py > contact_group.py
sed -i 's/Host/Contact/g contact_group.py
```
similarly test suite

**Comment by robin-tribe29** [comment]
Hi @msekania and thanks for the continuous contributions!
We are a little swamped right now, but I would target this feature for `0.12.0`, pending review of course.

**Comment by msekania** [comment]
Hi @robin-tribe29,

somehow this close similarity of contact and host groups does not give me a rest.
I have also checked and service group rest API interface is also quite similar.
I do not know, whether this similarity will also stay in the future, but in case, I have a group module written that combines all this three group management in one (including test suite).

https://github.com/msekania/ansible-collection-tribe29.checkmk/tree/feature-groups

In current version, there is a group_type field which takes one of ["contact", "host", "service"] values, and the rest is provided either by group_name (instead of host_group_name,  contact_group_name) and title or list of dict-s named 'groups' (instead of host_group,  contact_group) with name and title entries.
I can also add a backward compatibility features.

Alternatively, I can rewrite the module so that group_type field is removed and choice is made by providing:
- host_group_name or host_groups;
- contact_group_name or contact_groups;
- service_group_name or service_groups;

Should I make an another pull request?
We can decide then how to proceed.

Best,
Michael

**Comment by robin-tribe29** [comment]
Hi @msekania, we are already discussing this internally, but have not reached a definite conclusion. We lean towards dedicated modules but shared code base. But that is quite its own topic. How do you feel about merging this feature for now, as it is ready. I created a dedicated issue, where we can discuss the matter in depth.

**Review by lgetwan — APPROVED** [review]
I have successfully tested the code!

**Pull request merged**
