### PR TITLE
Fix cfe support

### PR DESCRIPTION
**Pull request by robin-tribe29**
## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

#119 

## What is the new behavior?

CFE is properly supported by the agent role.

### CODE REVIEW

**Comment by robin-tribe29** [comment]
@diademiemi would you take a quick look?

**Comment by diademiemi** [comment]
Just to be sure, CFE = Free / Enterprise trail edition?

**Comment by robin-tribe29** [comment]
Affirmative.

**Comment by diademiemi** [comment]
If I'm understanding correctly, the issue before was that CFE wouldn't count to run the enterprise edition tasks since those had the when statements set to only allow "cee"? But CFE is a trial of the enterprise edition so it does have those features available, so they should run. 
If that was the only issue before then I think this is a good approach to solving that. 

The integration test fails look unrelated, is that correct?

**Comment by robin-tribe29** [comment]
Yes, your understanding is correct. :+1: 
I was thinking about possible better approaches from an Ansible point of view.
Checkmk related we are good here.

Yes, the integration tests are unrelated, I am already investigating.

**Comment by diademiemi** [comment]
I think the logic is good, although I would suggest splitting the when statements, they are getting a bit long

For example I'd suggest 
```yml
  when: (checkmk_agent_edition == "cee" or checkmk_agent_edition == "cfe") and checkmk_agent_download_state.status != 200
```

```yml
  when: |
    (checkmk_agent_edition == "cee" or checkmk_agent_edition == "cfe")
    and checkmk_agent_download_state.status != 200
```

This makes the line shorter and easier to separate the part of the logic checking for the edition and which part is related to the download state. 
Same idea for the when statements for the TLS, updating, etc

**Pull request merged**
