### PR TITLE
Bugfix rule module folder handling

### PR DESCRIPTION
**Pull request by lgetwan**
## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

#195 

## What is the new behavior?

- When checking if the rule already exists, we now also take care of the rule's folder.
- Creating equal rules in multiple folders is now possible.

### CODE REVIEW

**Review by robin-tribe29 — APPROVED** [review]

**Comment by geof77** [comment]
Does not work very well.

I have tried a lot of different solutions. Here is my version that is working most of the time (as far as I've tested), although there might be security issues using eval ?:

```
def get_existing_rule(module, base_url, headers, ruleset, rule):
    # Get rules in ruleset
    rules = get_rules_in_ruleset(module, base_url, headers, ruleset)
    if rules is not None:
        # Loop through all rules
        for r in rules.get("value"):
            # Check if conditions, properties and values are the same
            if (
                # these are both strings so == works
                r["extensions"]["folder"] == rule["folder"]
                # == also works for dicts 
                and r["extensions"]["conditions"] == rule["conditions"]
                and r["extensions"]["properties"] == rule["properties"]
               # per API documentation value_raw must be a valid python object
               # so just eval() both and compare
                and eval(r["extensions"]["value_raw"]) == eval(rule["value_raw"])
            ):
                # If they are the same, return the ID
                return r["id"]
    return None
```

**Comment by geof77** [comment]
Thinking a bit further, what should this function really compare?
In properties, "description" and "comment" are not "functional", only "disabled" is significant.
So a rule with exactly the same folder, conditions and value_raw would have the same effect, regardless of the description and comment. I would exclude these two from the comparison.
What do you think?

**Comment by geof77** [comment]
So this would give us something like:

```
def get_existing_rule(module, base_url, headers, ruleset, rule):
    # Get rules in ruleset
    rules = get_rules_in_ruleset(module, base_url, headers, ruleset)
    # Remove comment and description from comparison
    rule["properties"].pop("comment")
    rule["properties"].pop("description")
    if rules is not None:
        # Loop through all rules
        for r in rules.get("value"):
            r["extensions"]["properties"].pop("comment")
            r["extensions"]["properties"].pop("description")
            # Check if conditions, properties and values are the same
            if (
                r["extensions"]["folder"] == rule["folder"]
                and r["extensions"]["conditions"] == rule["conditions"]
                and r["extensions"]["properties"] == rule["properties"]
                and eval(r["extensions"]["value_raw"]) == eval(rule["value_raw"])
            ):
                # If they are the same, return the ID
                return r["id"]
    return None
```

**Comment by geof77** [comment]
@lgetwan , @robin-tribe29 please review as the existing function breaks things and I can't get integration tests to succeed for PR #231

**Comment by lgetwan** [comment]
@geoff: Please see my comment in #186: https://github.com/tribe29/ansible-collection-tribe29.checkmk/issues/186#issuecomment-1396692373

**Comment by geof77** [comment]
@lgetwan : The PR introduces an error in the examples. "folder" and "location" are mutually exclusive. "folder" is deprecated and the value is picked up from location.

**Comment by lgetwan** [comment]
@geof77: True! But gladly, your PR #223 fixed this. Thanks. :-)

**Pull request merged**
